export type SupportedLocale = 'en' | 'pt' | 'es';

export const DEFAULT_LOCALE: SupportedLocale =
  (import.meta.env?.VITE_APP_LOCALE as SupportedLocale) || 'en';

type TranslationTable = Record<string, string>;

const translations: Record<SupportedLocale, TranslationTable> = {
  en: {
    'nav.overview': 'Overview',
    'nav.payments': 'Payments',
    'nav.analytics': 'Analytics',
    'nav.accounts': 'Accounts',
    'nav.withdraw': 'Withdraw',
    'nav.whitelist': 'Whitelist',
    'nav.addUser': 'Add User',
    'nav.templates': 'Templates',
    'nav.settings': 'Settings',
    'nav.section.overview': 'Overview',
    'nav.section.actions': 'Actions',
    'nav.section.system': 'System',

    'layout.brand.title': 'Crossramp',
    'layout.brand.subtitle': 'Dashboard',

    'write.badge': 'WRITE ACTION',

    'form.addUser.title': 'Add User',
    'form.addUser.description': 'Create a new user account. This action requires MFA verification.',
    'form.addUser.name': 'Full Name',
    'form.addUser.email': 'Email',
    'form.addUser.role': 'Role',
    'form.addUser.role.placeholder': 'Select role...',
    'form.addUser.role.user': 'User',
    'form.addUser.role.admin': 'Admin',
    'form.addUser.role.viewer': 'Viewer',

    'form.whitelist.title': 'Add to Whitelist',
    'form.whitelist.description': 'Add an address to the whitelist. This action requires MFA verification.',
    'form.whitelist.currency': 'Currency',
    'form.whitelist.network': 'Network',
    'form.whitelist.label': 'Wallet Label',
    'form.whitelist.label.helper': 'A friendly name to identify this wallet',
    'form.whitelist.address': 'Address',
    'form.whitelist.address.helper': 'wallet address',
    'form.whitelist.address.pix': 'PIX key',
    'form.whitelist.reason': 'Reason',

    'form.withdraw.title': 'Withdrawal Request',
    'form.withdraw.description': 'Submit a withdrawal request. This action requires MFA verification.',
    'form.withdraw.account': 'From Account',
    'form.withdraw.account.helper': 'Select the account to withdraw from',
    'form.withdraw.type': 'Withdraw As',
    'form.withdraw.type.same': 'Same Currency',
    'form.withdraw.type.same.helper': 'Direct withdrawal via {network}',
    'form.withdraw.type.brl': 'Convert to BRL',
    'form.withdraw.type.brl.helper': 'Automatic conversion, receive via PIX',
    'form.withdraw.amount': 'Amount',
    'form.withdraw.amount.helper': 'Select an account first',
    'form.withdraw.wallet': 'To Wallet Address',
    'form.withdraw.wallet.pix': 'To PIX Address',
    'form.withdraw.wallet.placeholder': 'Select whitelisted wallet',
    'form.withdraw.wallet.placeholder.pix': 'Select PIX address',
    'form.withdraw.wallet.none': 'No whitelisted wallets available',
    'form.withdraw.wallet.none.pix': 'No whitelisted PIX addresses available',
    'form.withdraw.note': 'Note (Optional)',

    'protectedForm.success': '✓ Action completed successfully',
    'protectedForm.error': '✗ Action failed. Please try again.',
    'protectedForm.submit.mfa': 'Submit (Requires MFA)',
    'protectedForm.submit': 'Submit',
    'protectedForm.processing': 'Processing...',

    'mfa.title': 'Two-Factor Authentication',
    'mfa.description': 'This action requires additional verification',
    'mfa.prompt': 'Enter the 6-digit code from your authenticator app',
    'mfa.cancel': 'Cancel',
    'mfa.verify': 'Verify & Submit',
    'mfa.error': 'Please enter a 6-digit code',
    'mfa.invalid': 'Invalid verification code. Please try again.',

    'charts.revenue.title': 'Revenue Overview',
    'charts.revenue.description': 'Monthly revenue and expenses from read-model database',
    'charts.userActivity.title': 'User Activity',
    'charts.userActivity.description': 'Daily active and inactive users',
    'charts.transactions.title': 'Transaction Volume',
    'charts.transactions.description': 'Hourly transaction count',
  },
  pt: {
    'nav.overview': 'Visão geral',
    'nav.payments': 'Pagamentos',
    'nav.analytics': 'Analytics',
    'nav.accounts': 'Contas',
    'nav.withdraw': 'Saque',
    'nav.whitelist': 'Whitelist',
    'nav.addUser': 'Adicionar usuário',
    'nav.templates': 'Templates',
    'nav.settings': 'Configurações',
    'nav.section.overview': 'Visão geral',
    'nav.section.actions': 'Ações',
    'nav.section.system': 'Sistema',

    'layout.brand.title': 'Crossramp',
    'layout.brand.subtitle': 'Dashboard',

    'write.badge': 'AÇÃO DE ESCRITA',

    'form.addUser.title': 'Adicionar usuário',
    'form.addUser.description': 'Criar uma nova conta de usuário. Esta ação requer verificação MFA.',
    'form.addUser.name': 'Nome completo',
    'form.addUser.email': 'Email',
    'form.addUser.role': 'Função',
    'form.addUser.role.placeholder': 'Selecione a função...',
    'form.addUser.role.user': 'Usuário',
    'form.addUser.role.admin': 'Admin',
    'form.addUser.role.viewer': 'Leitor',

    'form.whitelist.title': 'Adicionar ao whitelist',
    'form.whitelist.description': 'Adicionar um endereço ao whitelist. Esta ação requer verificação MFA.',
    'form.whitelist.currency': 'Moeda',
    'form.whitelist.network': 'Rede',
    'form.whitelist.label': 'Nome da carteira',
    'form.whitelist.label.helper': 'Um nome amigável para identificar esta carteira',
    'form.whitelist.address': 'Endereço',
    'form.whitelist.address.helper': 'endereço da carteira',
    'form.whitelist.address.pix': 'Chave PIX',
    'form.whitelist.reason': 'Motivo',

    'form.withdraw.title': 'Solicitação de saque',
    'form.withdraw.description': 'Envie uma solicitação de saque. Esta ação requer verificação MFA.',
    'form.withdraw.account': 'Da conta',
    'form.withdraw.account.helper': 'Selecione a conta para sacar',
    'form.withdraw.type': 'Sacar como',
    'form.withdraw.type.same': 'Mesma moeda',
    'form.withdraw.type.same.helper': 'Saque direto via {network}',
    'form.withdraw.type.brl': 'Converter para BRL',
    'form.withdraw.type.brl.helper': 'Conversão automática, receba via PIX',
    'form.withdraw.amount': 'Valor',
    'form.withdraw.amount.helper': 'Selecione uma conta primeiro',
    'form.withdraw.wallet': 'Para endereço da carteira',
    'form.withdraw.wallet.pix': 'Para endereço PIX',
    'form.withdraw.wallet.placeholder': 'Selecione uma carteira whitelist',
    'form.withdraw.wallet.placeholder.pix': 'Selecione endereço PIX',
    'form.withdraw.wallet.none': 'Nenhuma carteira whitelist disponível',
    'form.withdraw.wallet.none.pix': 'Nenhum endereço PIX whitelist disponível',
    'form.withdraw.note': 'Observação (opcional)',

    'protectedForm.success': '✓ Ação concluída com sucesso',
    'protectedForm.error': '✗ Ação falhou. Tente novamente.',
    'protectedForm.submit.mfa': 'Enviar (requer MFA)',
    'protectedForm.submit': 'Enviar',
    'protectedForm.processing': 'Processando...',

    'mfa.title': 'Autenticação em duas etapas',
    'mfa.description': 'Esta ação requer verificação adicional',
    'mfa.prompt': 'Digite o código de 6 dígitos do seu app autenticador',
    'mfa.cancel': 'Cancelar',
    'mfa.verify': 'Verificar e enviar',
    'mfa.error': 'Insira um código de 6 dígitos',
    'mfa.invalid': 'Código inválido. Tente novamente.',

    'charts.revenue.title': 'Visão geral de receita',
    'charts.revenue.description': 'Receita e despesas mensais do banco de leitura',
    'charts.userActivity.title': 'Atividade de usuários',
    'charts.userActivity.description': 'Usuários ativos e inativos por dia',
    'charts.transactions.title': 'Volume de transações',
    'charts.transactions.description': 'Contagem horária de transações',
  },
  es: {
    'nav.overview': 'Resumen',
    'nav.payments': 'Pagos',
    'nav.analytics': 'Analítica',
    'nav.accounts': 'Cuentas',
    'nav.withdraw': 'Retiro',
    'nav.whitelist': 'Whitelist',
    'nav.addUser': 'Agregar usuario',
    'nav.templates': 'Plantillas',
    'nav.settings': 'Configuración',
    'nav.section.overview': 'Resumen',
    'nav.section.actions': 'Acciones',
    'nav.section.system': 'Sistema',

    'layout.brand.title': 'Crossramp',
    'layout.brand.subtitle': 'Dashboard',

    'write.badge': 'ACCIÓN DE ESCRITURA',

    'form.addUser.title': 'Agregar usuario',
    'form.addUser.description': 'Crear una nueva cuenta de usuario. Esta acción requiere verificación MFA.',
    'form.addUser.name': 'Nombre completo',
    'form.addUser.email': 'Correo electrónico',
    'form.addUser.role': 'Rol',
    'form.addUser.role.placeholder': 'Seleccionar rol...',
    'form.addUser.role.user': 'Usuario',
    'form.addUser.role.admin': 'Admin',
    'form.addUser.role.viewer': 'Lector',

    'form.whitelist.title': 'Agregar a whitelist',
    'form.whitelist.description': 'Agregar una dirección a la whitelist. Esta acción requiere verificación MFA.',
    'form.whitelist.currency': 'Moneda',
    'form.whitelist.network': 'Red',
    'form.whitelist.label': 'Nombre de la billetera',
    'form.whitelist.label.helper': 'Un nombre amigable para identificar esta billetera',
    'form.whitelist.address': 'Dirección',
    'form.whitelist.address.helper': 'dirección de la billetera',
    'form.whitelist.address.pix': 'Clave PIX',
    'form.whitelist.reason': 'Motivo',

    'form.withdraw.title': 'Solicitud de retiro',
    'form.withdraw.description': 'Envíe una solicitud de retiro. Esta acción requiere verificación MFA.',
    'form.withdraw.account': 'Desde la cuenta',
    'form.withdraw.account.helper': 'Seleccione la cuenta para retirar',
    'form.withdraw.type': 'Retirar como',
    'form.withdraw.type.same': 'Misma moneda',
    'form.withdraw.type.same.helper': 'Retiro directo vía {network}',
    'form.withdraw.type.brl': 'Convertir a BRL',
    'form.withdraw.type.brl.helper': 'Conversión automática, reciba vía PIX',
    'form.withdraw.amount': 'Monto',
    'form.withdraw.amount.helper': 'Seleccione una cuenta primero',
    'form.withdraw.wallet': 'A dirección de billetera',
    'form.withdraw.wallet.pix': 'A dirección PIX',
    'form.withdraw.wallet.placeholder': 'Seleccione billetera whitelist',
    'form.withdraw.wallet.placeholder.pix': 'Seleccione dirección PIX',
    'form.withdraw.wallet.none': 'No hay billeteras whitelist disponibles',
    'form.withdraw.wallet.none.pix': 'No hay direcciones PIX whitelist disponibles',
    'form.withdraw.note': 'Nota (opcional)',

    'protectedForm.success': '✓ Acción completada con éxito',
    'protectedForm.error': '✗ La acción falló. Inténtelo de nuevo.',
    'protectedForm.submit.mfa': 'Enviar (requiere MFA)',
    'protectedForm.submit': 'Enviar',
    'protectedForm.processing': 'Procesando...',

    'mfa.title': 'Autenticación de dos factores',
    'mfa.description': 'Esta acción requiere verificación adicional',
    'mfa.prompt': 'Ingrese el código de 6 dígitos de su app autenticador',
    'mfa.cancel': 'Cancelar',
    'mfa.verify': 'Verificar y enviar',
    'mfa.error': 'Ingrese un código de 6 dígitos',
    'mfa.invalid': 'Código inválido. Intente nuevamente.',

    'charts.revenue.title': 'Resumen de ingresos',
    'charts.revenue.description': 'Ingresos y gastos mensuales del modelo de lectura',
    'charts.userActivity.title': 'Actividad de usuarios',
    'charts.userActivity.description': 'Usuarios activos e inactivos por día',
    'charts.transactions.title': 'Volumen de transacciones',
    'charts.transactions.description': 'Cantidad de transacciones por hora',
  },
};

export function translate(key: string, locale: SupportedLocale = DEFAULT_LOCALE): string {
  const table = translations[locale] || translations.en;
  return table[key] ?? translations.en[key] ?? key;
}

export function formatString(
  template: string,
  variables: Record<string, string | number>
): string {
  return Object.entries(variables).reduce(
    (acc, [token, value]) => acc.replaceAll(`{${token}}`, String(value)),
    template
  );
}
