export type SupportedLocale = 'en' | 'pt' | 'es';

export const DEFAULT_LOCALE: SupportedLocale =
  (import.meta.env?.VITE_APP_LOCALE as SupportedLocale) || 'en';

type TranslationTable = Record<string, string>;

const translations: Record<SupportedLocale, TranslationTable> = {
  en: {
    'nav.overview': 'Overview',
    'nav.payments': 'Payments',
    'nav.analytics': 'Analytics',
    'nav.accounts': 'Accounts',
    'nav.withdraw': 'Withdraw',
    'nav.whitelist': 'Whitelist',
    'nav.addUser': 'Add User',
    'nav.templates': 'Templates',
    'nav.settings': 'Settings',
    'nav.section.overview': 'Overview',
    'nav.section.actions': 'Actions',
    'nav.section.system': 'System',

    'layout.brand.title': 'Crossramp',
    'layout.brand.subtitle': 'Dashboard',

    'write.badge': 'WRITE ACTION',

    'form.addUser.title': 'Add User',
    'form.addUser.description': 'Create a new user account. This action requires MFA verification.',
    'form.addUser.name': 'Full Name',
    'form.addUser.email': 'Email',
    'form.addUser.role': 'Role',
    'form.addUser.role.placeholder': 'Select role...',
    'form.addUser.role.user': 'User',
    'form.addUser.role.admin': 'Admin',
    'form.addUser.role.viewer': 'Viewer',

    'form.whitelist.title': 'Add to Whitelist',
    'form.whitelist.description': 'Add an address to the whitelist. This action requires MFA verification.',
    'form.whitelist.currency': 'Currency',
    'form.whitelist.network': 'Network',
    'form.whitelist.label': 'Wallet Label',
    'form.whitelist.label.helper': 'A friendly name to identify this wallet',
    'form.whitelist.address': 'Address',
    'form.whitelist.address.helper': 'wallet address',
    'form.whitelist.address.pix': 'PIX key',
    'form.whitelist.reason': 'Reason',

    'form.withdraw.title': 'Withdrawal Request',
    'form.withdraw.description': 'Submit a withdrawal request. This action requires MFA verification.',
    'form.withdraw.account': 'From Account',
    'form.withdraw.account.helper': 'Select the account to withdraw from',
    'form.withdraw.type': 'Withdraw As',
    'form.withdraw.type.same': 'Same Currency',
    'form.withdraw.type.same.helper': 'Direct withdrawal via {network}',
    'form.withdraw.type.brl': 'Convert to BRL',
    'form.withdraw.type.brl.helper': 'Automatic conversion, receive via PIX',
    'form.withdraw.amount': 'Amount',
    'form.withdraw.amount.helper': 'Select an account first',
    'form.withdraw.wallet': 'To Wallet Address',
    'form.withdraw.wallet.pix': 'To PIX Address',
    'form.withdraw.wallet.placeholder': 'Select whitelisted wallet',
    'form.withdraw.wallet.placeholder.pix': 'Select PIX address',
    'form.withdraw.wallet.none': 'No whitelisted wallets available',
    'form.withdraw.wallet.none.pix': 'No whitelisted PIX addresses available',
    'form.withdraw.note': 'Note (Optional)',

    'protectedForm.success': '✓ Action completed successfully',
    'protectedForm.error': '✗ Action failed. Please try again.',
    'protectedForm.submit.mfa': 'Submit (Requires MFA)',
    'protectedForm.submit': 'Submit',
    'protectedForm.processing': 'Processing...',

    'mfa.title': 'Two-Factor Authentication',
    'mfa.description': 'This action requires additional verification',
    'mfa.prompt': 'Enter the 6-digit code from your authenticator app',
    'mfa.cancel': 'Cancel',
    'mfa.verify': 'Verify & Submit',
    'mfa.error': 'Please enter a 6-digit code',
    'mfa.invalid': 'Invalid verification code. Please try again.',

    'charts.revenue.title': 'Revenue Overview',
    'charts.revenue.description': 'Monthly revenue and expenses from read-model database',
    'charts.userActivity.title': 'User Activity',
    'charts.userActivity.description': 'Daily active and inactive users',
    'charts.transactions.title': 'Transaction Volume',
    'charts.transactions.description': 'Hourly transaction count',

    // Dashboard view
    'dashboard.balance.label': 'Available balance',
    'dashboard.balance.meta': 'BRL · settles in USDT',
    'dashboard.balance.updated': 'Updated 2 min ago',
    'dashboard.action.receive': 'Receive payment',
    'dashboard.action.withdraw': 'Withdraw',
    'dashboard.today.title': 'Today',
    'dashboard.today.viewDetails': 'View details',
    'dashboard.today.paymentsReceived': 'Payments received',
    'dashboard.today.paymentsPending': 'Payments pending',
    'dashboard.today.fees': 'Fees',
    'dashboard.recent.title': 'Recent activity',
    'dashboard.recent.viewAll': 'View all',
    'dashboard.status.title': 'Payment status',
    'dashboard.status.completed': 'Completed',
    'dashboard.status.pending': 'Pending',
    'dashboard.advanced.toggle': 'Show advanced analytics',

    // Onboarding widget
    'onboarding.title': 'Finish onboarding',
    'onboarding.subtitle': 'Complete these four steps to unlock write actions.',
    'onboarding.progress': '{completed} of {total} done',
    'onboarding.step.kyc.title': 'Complete KYC with Facial Recognition',
    'onboarding.step.kyc.description': 'Verify your identity securely with a quick liveness check.',
    'onboarding.step.kyc.helper': 'Takes ~2 minutes. Required before moving funds.',
    'onboarding.step.kyc.badge': 'Compliance',
    'onboarding.step.mfa.title': 'Setup MFA',
    'onboarding.step.mfa.description': 'Add an authenticator app or hardware key for write actions.',
    'onboarding.step.mfa.helper': 'Required to authorize withdrawals and whitelist changes.',
    'onboarding.step.mfa.badge': 'Security',
    'onboarding.step.template.title': 'Create a Template',
    'onboarding.step.template.description': 'Define a reusable payout or invoice template.',
    'onboarding.step.template.helper': 'Keeps write commands consistent for your team.',
    'onboarding.step.checkout.title': 'Create a checkout/payment',
    'onboarding.step.checkout.description': 'Spin up a sample checkout to validate the flow end-to-end.',
    'onboarding.step.checkout.helper': 'Simulates API-side callback processing.',
    'onboarding.completed.label': 'Completed',
    'onboarding.syncing': 'Syncing…',
    'onboarding.note': 'Writes remain API-driven; callbacks will validate each completed step asynchronously via Auth0/KYC services.',
    'onboarding.scrollCta': 'Continue Setup',
  },
  pt: {
    'nav.overview': 'Visão geral',
    'nav.payments': 'Pagamentos',
    'nav.analytics': 'Analytics',
    'nav.accounts': 'Contas',
    'nav.withdraw': 'Saque',
    'nav.whitelist': 'Whitelist',
    'nav.addUser': 'Adicionar usuário',
    'nav.templates': 'Templates',
    'nav.settings': 'Configurações',
    'nav.section.overview': 'Visão geral',
    'nav.section.actions': 'Ações',
    'nav.section.system': 'Sistema',

    'layout.brand.title': 'Crossramp',
    'layout.brand.subtitle': 'Dashboard',

    'write.badge': 'AÇÃO DE ESCRITA',

    'form.addUser.title': 'Adicionar usuário',
    'form.addUser.description': 'Criar uma nova conta de usuário. Esta ação requer verificação MFA.',
    'form.addUser.name': 'Nome completo',
    'form.addUser.email': 'Email',
    'form.addUser.role': 'Função',
    'form.addUser.role.placeholder': 'Selecione a função...',
    'form.addUser.role.user': 'Usuário',
    'form.addUser.role.admin': 'Admin',
    'form.addUser.role.viewer': 'Leitor',

    'form.whitelist.title': 'Adicionar ao whitelist',
    'form.whitelist.description': 'Adicionar um endereço ao whitelist. Esta ação requer verificação MFA.',
    'form.whitelist.currency': 'Moeda',
    'form.whitelist.network': 'Rede',
    'form.whitelist.label': 'Nome da carteira',
    'form.whitelist.label.helper': 'Um nome amigável para identificar esta carteira',
    'form.whitelist.address': 'Endereço',
    'form.whitelist.address.helper': 'endereço da carteira',
    'form.whitelist.address.pix': 'Chave PIX',
    'form.whitelist.reason': 'Motivo',

    'form.withdraw.title': 'Solicitação de saque',
    'form.withdraw.description': 'Envie uma solicitação de saque. Esta ação requer verificação MFA.',
    'form.withdraw.account': 'Da conta',
    'form.withdraw.account.helper': 'Selecione a conta para sacar',
    'form.withdraw.type': 'Sacar como',
    'form.withdraw.type.same': 'Mesma moeda',
    'form.withdraw.type.same.helper': 'Saque direto via {network}',
    'form.withdraw.type.brl': 'Converter para BRL',
    'form.withdraw.type.brl.helper': 'Conversão automática, receba via PIX',
    'form.withdraw.amount': 'Valor',
    'form.withdraw.amount.helper': 'Selecione uma conta primeiro',
    'form.withdraw.wallet': 'Para endereço da carteira',
    'form.withdraw.wallet.pix': 'Para endereço PIX',
    'form.withdraw.wallet.placeholder': 'Selecione uma carteira whitelist',
    'form.withdraw.wallet.placeholder.pix': 'Selecione endereço PIX',
    'form.withdraw.wallet.none': 'Nenhuma carteira whitelist disponível',
    'form.withdraw.wallet.none.pix': 'Nenhum endereço PIX whitelist disponível',
    'form.withdraw.note': 'Observação (opcional)',

    'protectedForm.success': '✓ Ação concluída com sucesso',
    'protectedForm.error': '✗ Ação falhou. Tente novamente.',
    'protectedForm.submit.mfa': 'Enviar (requer MFA)',
    'protectedForm.submit': 'Enviar',
    'protectedForm.processing': 'Processando...',

    'mfa.title': 'Autenticação em duas etapas',
    'mfa.description': 'Esta ação requer verificação adicional',
    'mfa.prompt': 'Digite o código de 6 dígitos do seu app autenticador',
    'mfa.cancel': 'Cancelar',
    'mfa.verify': 'Verificar e enviar',
    'mfa.error': 'Insira um código de 6 dígitos',
    'mfa.invalid': 'Código inválido. Tente novamente.',

    'charts.revenue.title': 'Visão geral de receita',
    'charts.revenue.description': 'Receita e despesas mensais do banco de leitura',
    'charts.userActivity.title': 'Atividade de usuários',
    'charts.userActivity.description': 'Usuários ativos e inativos por dia',
    'charts.transactions.title': 'Volume de transações',
    'charts.transactions.description': 'Contagem horária de transações',

    // Dashboard view
    'dashboard.balance.label': 'Saldo disponível',
    'dashboard.balance.meta': 'BRL · liquida em USDT',
    'dashboard.balance.updated': 'Atualizado há 2 min',
    'dashboard.action.receive': 'Receber pagamento',
    'dashboard.action.withdraw': 'Sacar',
    'dashboard.today.title': 'Hoje',
    'dashboard.today.viewDetails': 'Ver detalhes',
    'dashboard.today.paymentsReceived': 'Pagamentos recebidos',
    'dashboard.today.paymentsPending': 'Pagamentos pendentes',
    'dashboard.today.fees': 'Taxas',
    'dashboard.recent.title': 'Atividade recente',
    'dashboard.recent.viewAll': 'Ver tudo',
    'dashboard.status.title': 'Status de pagamento',
    'dashboard.status.completed': 'Concluídos',
    'dashboard.status.pending': 'Pendentes',
    'dashboard.advanced.toggle': 'Mostrar analytics avançado',

    // Onboarding widget
    'onboarding.title': 'Conclua a ativação',
    'onboarding.subtitle': 'Finalize as quatro etapas para liberar ações de escrita.',
    'onboarding.progress': '{completed} de {total} concluídas',
    'onboarding.step.kyc.title': 'Completar KYC com reconhecimento facial',
    'onboarding.step.kyc.description': 'Verifique sua identidade com prova de vida rápida.',
    'onboarding.step.kyc.helper': 'Leva ~2 minutos. Necessário antes de mover fundos.',
    'onboarding.step.kyc.badge': 'Compliance',
    'onboarding.step.mfa.title': 'Configurar MFA',
    'onboarding.step.mfa.description': 'Adicione app autenticador ou chave física para ações de escrita.',
    'onboarding.step.mfa.helper': 'Obrigatório para saques e whitelist.',
    'onboarding.step.mfa.badge': 'Segurança',
    'onboarding.step.template.title': 'Criar um template',
    'onboarding.step.template.description': 'Defina um template reutilizável de pagamento/fatura.',
    'onboarding.step.template.helper': 'Mantém comandos de escrita consistentes para o time.',
    'onboarding.step.checkout.title': 'Criar um checkout/pagamento',
    'onboarding.step.checkout.description': 'Monte um checkout de teste para validar o fluxo fim a fim.',
    'onboarding.step.checkout.helper': 'Simula processamento de callback no backend.',
    'onboarding.completed.label': 'Concluído',
    'onboarding.syncing': 'Sincronizando…',
    'onboarding.note': 'Escritas seguem via API; callbacks validarão cada etapa concluída com Auth0/KYC.',
    'onboarding.scrollCta': 'Continuar configuração',
  },
  es: {
    'nav.overview': 'Resumen',
    'nav.payments': 'Pagos',
    'nav.analytics': 'Analítica',
    'nav.accounts': 'Cuentas',
    'nav.withdraw': 'Retiro',
    'nav.whitelist': 'Whitelist',
    'nav.addUser': 'Agregar usuario',
    'nav.templates': 'Plantillas',
    'nav.settings': 'Configuración',
    'nav.section.overview': 'Resumen',
    'nav.section.actions': 'Acciones',
    'nav.section.system': 'Sistema',

    'layout.brand.title': 'Crossramp',
    'layout.brand.subtitle': 'Dashboard',

    'write.badge': 'ACCIÓN DE ESCRITURA',

    'form.addUser.title': 'Agregar usuario',
    'form.addUser.description': 'Crear una nueva cuenta de usuario. Esta acción requiere verificación MFA.',
    'form.addUser.name': 'Nombre completo',
    'form.addUser.email': 'Correo electrónico',
    'form.addUser.role': 'Rol',
    'form.addUser.role.placeholder': 'Seleccionar rol...',
    'form.addUser.role.user': 'Usuario',
    'form.addUser.role.admin': 'Admin',
    'form.addUser.role.viewer': 'Lector',

    'form.whitelist.title': 'Agregar a whitelist',
    'form.whitelist.description': 'Agregar una dirección a la whitelist. Esta acción requiere verificación MFA.',
    'form.whitelist.currency': 'Moneda',
    'form.whitelist.network': 'Red',
    'form.whitelist.label': 'Nombre de la billetera',
    'form.whitelist.label.helper': 'Un nombre amigable para identificar esta billetera',
    'form.whitelist.address': 'Dirección',
    'form.whitelist.address.helper': 'dirección de la billetera',
    'form.whitelist.address.pix': 'Clave PIX',
    'form.whitelist.reason': 'Motivo',

    'form.withdraw.title': 'Solicitud de retiro',
    'form.withdraw.description': 'Envíe una solicitud de retiro. Esta acción requiere verificación MFA.',
    'form.withdraw.account': 'Desde la cuenta',
    'form.withdraw.account.helper': 'Seleccione la cuenta para retirar',
    'form.withdraw.type': 'Retirar como',
    'form.withdraw.type.same': 'Misma moneda',
    'form.withdraw.type.same.helper': 'Retiro directo vía {network}',
    'form.withdraw.type.brl': 'Convertir a BRL',
    'form.withdraw.type.brl.helper': 'Conversión automática, reciba vía PIX',
    'form.withdraw.amount': 'Monto',
    'form.withdraw.amount.helper': 'Seleccione una cuenta primero',
    'form.withdraw.wallet': 'A dirección de billetera',
    'form.withdraw.wallet.pix': 'A dirección PIX',
    'form.withdraw.wallet.placeholder': 'Seleccione billetera whitelist',
    'form.withdraw.wallet.placeholder.pix': 'Seleccione dirección PIX',
    'form.withdraw.wallet.none': 'No hay billeteras whitelist disponibles',
    'form.withdraw.wallet.none.pix': 'No hay direcciones PIX whitelist disponibles',
    'form.withdraw.note': 'Nota (opcional)',

    'protectedForm.success': '✓ Acción completada con éxito',
    'protectedForm.error': '✗ La acción falló. Inténtelo de nuevo.',
    'protectedForm.submit.mfa': 'Enviar (requiere MFA)',
    'protectedForm.submit': 'Enviar',
    'protectedForm.processing': 'Procesando...',

    'mfa.title': 'Autenticación de dos factores',
    'mfa.description': 'Esta acción requiere verificación adicional',
    'mfa.prompt': 'Ingrese el código de 6 dígitos de su app autenticador',
    'mfa.cancel': 'Cancelar',
    'mfa.verify': 'Verificar y enviar',
    'mfa.error': 'Ingrese un código de 6 dígitos',
    'mfa.invalid': 'Código inválido. Intente nuevamente.',

    'charts.revenue.title': 'Resumen de ingresos',
    'charts.revenue.description': 'Ingresos y gastos mensuales del modelo de lectura',
    'charts.userActivity.title': 'Actividad de usuarios',
    'charts.userActivity.description': 'Usuarios activos e inactivos por día',
    'charts.transactions.title': 'Volumen de transacciones',
    'charts.transactions.description': 'Cantidad de transacciones por hora',

    // Dashboard view
    'dashboard.balance.label': 'Saldo disponible',
    'dashboard.balance.meta': 'BRL · liquida en USDT',
    'dashboard.balance.updated': 'Actualizado hace 2 min',
    'dashboard.action.receive': 'Recibir pago',
    'dashboard.action.withdraw': 'Retirar',
    'dashboard.today.title': 'Hoy',
    'dashboard.today.viewDetails': 'Ver detalles',
    'dashboard.today.paymentsReceived': 'Pagos recibidos',
    'dashboard.today.paymentsPending': 'Pagos pendientes',
    'dashboard.today.fees': 'Comisiones',
    'dashboard.recent.title': 'Actividad reciente',
    'dashboard.recent.viewAll': 'Ver todo',
    'dashboard.status.title': 'Estado de pagos',
    'dashboard.status.completed': 'Completados',
    'dashboard.status.pending': 'Pendientes',
    'dashboard.advanced.toggle': 'Mostrar analíticas avanzadas',

    // Onboarding widget
    'onboarding.title': 'Completa la activación',
    'onboarding.subtitle': 'Finaliza estos cuatro pasos para habilitar acciones de escritura.',
    'onboarding.progress': '{completed} de {total} completados',
    'onboarding.step.kyc.title': 'Completar KYC con reconocimiento facial',
    'onboarding.step.kyc.description': 'Verifica tu identidad con una prueba de vida rápida.',
    'onboarding.step.kyc.helper': 'Toma ~2 minutos. Requerido antes de mover fondos.',
    'onboarding.step.kyc.badge': 'Cumplimiento',
    'onboarding.step.mfa.title': 'Configurar MFA',
    'onboarding.step.mfa.description': 'Agrega app autenticador o llave física para acciones de escritura.',
    'onboarding.step.mfa.helper': 'Obligatorio para retiros y whitelist.',
    'onboarding.step.mfa.badge': 'Seguridad',
    'onboarding.step.template.title': 'Crear una plantilla',
    'onboarding.step.template.description': 'Define una plantilla reutilizable de pago/factura.',
    'onboarding.step.template.helper': 'Mantiene los comandos de escritura consistentes para el equipo.',
    'onboarding.step.checkout.title': 'Crear un checkout/pago',
    'onboarding.step.checkout.description': 'Arma un checkout de prueba para validar el flujo end to end.',
    'onboarding.step.checkout.helper': 'Simula procesamiento de callback en el backend.',
    'onboarding.completed.label': 'Completado',
    'onboarding.syncing': 'Sincronizando…',
    'onboarding.note': 'Las escrituras siguen vía API; los callbacks validarán cada paso con Auth0/KYC.',
    'onboarding.scrollCta': 'Continuar configuración',
  },
};

export function translate(key: string, locale: SupportedLocale = DEFAULT_LOCALE): string {
  const table = translations[locale] || translations.en;
  return table[key] ?? translations.en[key] ?? key;
}

export function formatString(
  template: string,
  variables: Record<string, string | number>
): string {
  return Object.entries(variables).reduce(
    (acc, [token, value]) => acc.replaceAll(`{${token}}`, String(value)),
    template
  );
}
